package velord.university.model.miniPlayer.broadcast

//what can receive service
const val ACTION_STOP = "velord.university.STOP"
const val ACTION_PLAY = "velord.university.PlAY"
const val ACTION_LIKE = "velord.university.LIKE"
const val ACTION_UNLIKE = "velord.university.UNLIKE"
const val ACTION_SKIP_NEXT = "velord.university.SKIP_NEXT"
const val ACTION_SKIP_PREV = "velord.university.SKIP_PREV"
const val ACTION_REWIND = "velord.university.REWIND"
const val ACTION_SHUFFLE = "velord.university.SHUFFLE"
const val ACTION_UN_SHUFFLE = "velord.university.UN_SHUFFLE"
const val ACTION_LOOP = "velord.university.LOOP"
const val ACTION_LOOP_ALL = "velord.university.LOOP_ALL"
//what can receive ui
const val ACTION_STOP_UI = "velord.university.STOP_UI"
const val ACTION_PLAY_UI = "velord.university.PlAY_UI"
const val ACTION_LIKE_UI = "velord.university.LIKE_UI"
const val ACTION_UNLIKE_UI = "velord.university.UNLIKE_UI"
const val ACTION_SKIP_NEXT_UI = "velord.university.SKIP_NEXT_UI"
const val ACTION_SKIP_PREV_UI = "velord.university.SKIP_PREV_UI"
const val ACTION_REWIND_UI = "velord.university.REWIND_UI"
const val ACTION_SHUFFLE_UI = "velord.university.SHUFFLE_UI"
const val ACTION_UN_SHUFFLE_UI = "velord.university.UN_SHUFFLE_UI"
const val ACTION_LOOP_UI = "velord.university.LOOP_UI"
const val ACTION_LOOP_ALL_UI = "velord.university.LOOP_ALL_UI"
const val ACTION_NOT_LOOP_UI = "velord.university.NOT_LOOP_UI"
const val ACTION_SONG_ARTIST_UI = "velord.university.SONG_ARTIST_UI"
const val ACTION_SONG_NAME_UI = "velord.university.SONG_NAME_UI"
const val ACTION_SONG_HQ = "velord.university.SONG_HQ_UI"
const val ACTION_SONG_DURATION = "velord.university.SONG_DURATION_UI"